// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXwU-twoEDQ_pqvHqDXplXz4RAqP6ShlQ',
    appId: '1:886970546331:web:f77ecea7a401eaa2c12e3e',
    messagingSenderId: '886970546331',
    projectId: 'agus-proyect',
    authDomain: 'agus-proyect.firebaseapp.com',
    storageBucket: 'agus-proyect.firebasestorage.app',
    measurementId: 'G-ZWKXNRRD6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3GEMgK8-5ndaNVzYmGTB7fYIIM4XCdY',
    appId: '1:886970546331:android:d9076733bcd7bb2ac12e3e',
    messagingSenderId: '886970546331',
    projectId: 'agus-proyect',
    storageBucket: 'agus-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxY3qb8A5hTJOnzf18iAkNQXQBZ7HI4Zg',
    appId: '1:886970546331:ios:36be39fe8313dcf3c12e3e',
    messagingSenderId: '886970546331',
    projectId: 'agus-proyect',
    storageBucket: 'agus-proyect.firebasestorage.app',
    iosBundleId: 'com.example.holamundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxY3qb8A5hTJOnzf18iAkNQXQBZ7HI4Zg',
    appId: '1:886970546331:ios:36be39fe8313dcf3c12e3e',
    messagingSenderId: '886970546331',
    projectId: 'agus-proyect',
    storageBucket: 'agus-proyect.firebasestorage.app',
    iosBundleId: 'com.example.holamundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwU-twoEDQ_pqvHqDXplXz4RAqP6ShlQ',
    appId: '1:886970546331:web:26a0e6404a207adac12e3e',
    messagingSenderId: '886970546331',
    projectId: 'agus-proyect',
    authDomain: 'agus-proyect.firebaseapp.com',
    storageBucket: 'agus-proyect.firebasestorage.app',
    measurementId: 'G-MNMB9FYWWY',
  );
}
